### ISSUE TITLE
audio track in sdp causes crashes

### ISSUE THREAD

**Issue by fabianeichfeldt** [AxisCommunications/media-stream-library-js#121]
I've an Foscam camera which provides two media types in SDP:
console.log(sdp):
```
media: 
   [ { type: 'video',
       port: '0',
       proto: 'RTP/AVP',
       fmt: '96',
       connectionData: [Object],
       bwtype: 'AS',
       bandwidth: '96',
       rtpmap: [Object],
       range: 'npt=0-',
       fmtp: [Object],
       control: 'track1' },
     { type: 'audio',
       port: '0',
       proto: 'RTP/AVP',
       fmt: '0',
       connectionData: [Object],
       bwtype: 'AS',
       bandwidth: '64',
       control: 'track2' } ]
```
SDP from WireShark:
```
v=0
o=- 1547817039042595 1 IN IP4 10.0.1.135
s=IP Camera Video
i=videoMain
t=0 0
a=tool:LIVE555 Streaming Media v2014.02.10
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:IP Camera Video
a=x-qt-text-inf:videoMain
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:96
a=rtpmap:96 H264/90000
a=range:npt=0-
a=fmtp:96 packetization-mode=1;profile-level-id=640032;sprop-parameter-sets=Z2QAMqw0zAKAC1/wFqAgICgAAB9o7jwwh0MACfyAAJ/DXeXGhgAT+QABP4a7y4U=,aO48MA==
a=control:track1
m=audio 0 RTP/AVP 0
c=IN IP4 0.0.0.0
b=AS:64
a=control:track2
```

this causes trouble in
- boxbuilder.js
- mse-component.js
- rtspsession-component.js

by requesting media.rtpmap

**Proposal**: check type of media and skip if it isn't 'video'
I am preparing a PR for this

**Comment by steabert** [comment]
Skipping if it isn't 'video' wouldn't work because there are 'audio' encodings we do handle, and even metadata types that can be used. However, I saw in your PR that you just skip if the media does not have an `rtpmap`, which is fine as a work-around.

Better would be to actually handle static payload types, and let the eventual decision happen when the decoder is looking at the media types.
In your case this would mean that we parse the audio type as having `payloadType=0` (from `audio 0 RTP/AVP 0`) and derive the clock rate from a table.

**Comment by fabianeichfeldt** [comment]
not reproduceable anymore
