### ISSUE TITLE
es5 build should not replace existing window.Promise

### ISSUE THREAD

**Issue by jjfrankovich** [AxisCommunications/media-stream-library-js#289]
**Describe the bug**
My project uses a custom Promise implementation called bluebird:
https://github.com/petkaantonov/bluebird/blob/master/API.md

When media-stream-library.min.js runs (which was compiled from the master branch and built for es5) the window.Promise switches from our desired blueJay implementation to a different promise implement that is missing a few functions like Promise.finally.

Here is an example stack trace that we see after media-stream-library.min.js is loaded:

media-stream-library.min.js?version=1574257754418:8 Unhandled promise rejection TypeError: f.then(...).finally is not a function

Ideally, media-stream-library would check for the existence of window.Promise before replacing it.
Something like "window.Promise = window.Promise || media-stream-library.Promise;"

**Environment:**
 - OS: Windows
 - Browser Chrome
 - Version 6.0.3 built from master branch on 20191112 for es5; we needed the ios 12 fix and no npm version has been provided with that fix yet.

**Comment by steabert** [comment]
I've read about this issue and it seems to be a general problem with combining `core-js` and `bluebird`. There seems to be a solution with https://github.com/zloirock/core-js/issues/283 (https://github.com/zloirock/core-js#configurable-level-of-aggressiveness), but that would require you to rebuild the library with those options.

I'm hesitant to support this out-of-the-box, since I prefer to rely on `core-js` to do its job instead of making assumptions about someone's use of polyfills. They should only replace the `Promise` polyfill if it doesn't meet the requirements (so I guess that it's too strict for bluebird). If you can configure `core-js` with the less aggressive option we could add this to our documentation.

Another options would be to load bluebird after our minified bundle, if that's possible?
