### ISSUE TITLE
Local Start Works but Fails when Deployed.

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [AxisCommunications/media-stream-library-js#703]
**Describe the bug**
Locally when I start the implementation of the react multi stream, it works great. However when deployed I see the following error:

<img width="745" alt="Screen Shot 2022-08-16 at 2 28 17 PM" src="https://user-images.githubusercontent.com/78372056/184965537-9f4cb700-ac9e-4c13-871a-7c0297284280.png">

**To Reproduce**
I am really at a loss as to how to reproduce this, because this does not happen locally. Everything works great locally, just fails when the site has been deployed.

**Environment (please complete the following information):**
 - OS: macOS Monterey 12.5
 - Browser: Microsoft Edge, Chrome, Safari
 - Version: Latest

**Comment by steabert** [comment]
If you bundle it yourself, you'll need the alias when using vite. I'm not sure I understand "once actually deployed to a react site" ? Do you mean that when bundling with vite the alias doesn't work?

The pre-bundled distributions should work as well, since esbuild will respect the browser field in `package.json`.
